# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test-va-vdd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_f1717854b1764921a797f666eb3f9fa9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2eed95ffcf1d464d933fa1a7c3d8ee08 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f1717854b1764921a797f666eb3f9fa9 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test-va-vdd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fcf5424ade0a49eca5bff0b56e4ee4b0 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f1717854b1764921a797f666eb3f9fa9 }}/appsvc/staticsite:${{ github.sha }}'